//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMCServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.nmccentral.com/webservices/nmcmapi", ConfigurationName="NMCServiceReference.NMCLinkPortalSoap")]
    public interface NMCLinkPortalSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nmccentral.com/webservices/nmcmapi/ProcessData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ProcessDataAsync(string reqType, string secUser, string passWord, string csNo, string xmldata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nmccentral.com/webservices/nmcmapi/ProcessAppRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NMCServiceReference.ArrayOfXElement> ProcessAppRequestAsync(NMCServiceReference.InputParms inParms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nmccentral.com/webservices/nmcmapi/ProcessDataElementRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NMCServiceReference.ArrayOfXElement> ProcessDataElementRequestAsync(NMCServiceReference.InputParms inParms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nmccentral.com/webservices/nmcmapi/ProcessDataElementRequest2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NMCServiceReference.ArrayOfXElement> ProcessDataElementRequest2Async(NMCServiceReference.OnTestParms ontestParms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nmccentral.com/webservices/nmcmapi/GetAppToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetAppTokenAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nmccentral.com/webservices/nmcmapi/ProcessTwilioRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ProcessTwilioRequestAsync(string twilioUser, string twilioPIN, string accountNo, string codeWord, string processName, string testHours, string testFlag, string userName, string eventSeqNo);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nmccentral.com/webservices/nmcmapi")]
    public partial class InputParms
    {
        
        private System.Nullable<int> siteNoField;
        
        private System.Nullable<int> systemNoField;
        
        private System.Nullable<int> contactNoField;
        
        private string reqTypeField;
        
        private string secUserField;
        
        private string procNameField;
        
        private string csNoField;
        
        private string xmlDataField;
        
        private string appFlagField;
        
        private string passWordField;
        
        private string xmlStringField;
        
        private string pINField;
        
        private string codeWordField;
        
        private string sitePhoneField;
        
        private string panelCodeField;
        
        private System.Nullable<int> cust_noField;
        
        private string site_nameField;
        
        private string altIDField;
        
        private string email_addressField;
        
        private string contactPhoneField;
        
        private System.Nullable<int> empNoField;
        
        private string udf1Field;
        
        private string udf2Field;
        
        private string udf3Field;
        
        private string udf4Field;
        
        private System.Nullable<int> branchNoField;
        
        private System.Nullable<int> coNoField;
        
        private System.Nullable<int> installNoField;
        
        private System.Nullable<int> servcoNoField;
        
        private System.Nullable<int> corpAcctNoField;
        
        private string startDateField;
        
        private string tranDateField;
        
        private string endDateField;
        
        private System.Nullable<int> historyRowsField;
        
        private string openOnlyField;
        
        private string invoiceOnlyField;
        
        private string sortOrderField;
        
        private string useHistoryField;
        
        private string dbFlagField;
        
        private string startBillCodeField;
        
        private string endBillCodeField;
        
        private string hideReverseField;
        
        private string retAddrField;
        
        private System.Nullable<int> invFromField;
        
        private System.Nullable<int> invToField;
        
        private System.Nullable<int> spidField;
        
        private string emailFlagField;
        
        private System.Nullable<int> invFormNoField;
        
        private System.Nullable<int> invoiceNoField;
        
        private System.Nullable<int> ctactLinkNoField;
        
        private string processNameField;
        
        private string commentField;
        
        private decimal recdAmountField;
        
        private string serverNameField;
        
        private string dbNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> siteNo
        {
            get
            {
                return this.siteNoField;
            }
            set
            {
                this.siteNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> systemNo
        {
            get
            {
                return this.systemNoField;
            }
            set
            {
                this.systemNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> contactNo
        {
            get
            {
                return this.contactNoField;
            }
            set
            {
                this.contactNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string reqType
        {
            get
            {
                return this.reqTypeField;
            }
            set
            {
                this.reqTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string secUser
        {
            get
            {
                return this.secUserField;
            }
            set
            {
                this.secUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string procName
        {
            get
            {
                return this.procNameField;
            }
            set
            {
                this.procNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string csNo
        {
            get
            {
                return this.csNoField;
            }
            set
            {
                this.csNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string xmlData
        {
            get
            {
                return this.xmlDataField;
            }
            set
            {
                this.xmlDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string appFlag
        {
            get
            {
                return this.appFlagField;
            }
            set
            {
                this.appFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string passWord
        {
            get
            {
                return this.passWordField;
            }
            set
            {
                this.passWordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string xmlString
        {
            get
            {
                return this.xmlStringField;
            }
            set
            {
                this.xmlStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string PIN
        {
            get
            {
                return this.pINField;
            }
            set
            {
                this.pINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string codeWord
        {
            get
            {
                return this.codeWordField;
            }
            set
            {
                this.codeWordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string sitePhone
        {
            get
            {
                return this.sitePhoneField;
            }
            set
            {
                this.sitePhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string panelCode
        {
            get
            {
                return this.panelCodeField;
            }
            set
            {
                this.panelCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<int> cust_no
        {
            get
            {
                return this.cust_noField;
            }
            set
            {
                this.cust_noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string site_name
        {
            get
            {
                return this.site_nameField;
            }
            set
            {
                this.site_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string altID
        {
            get
            {
                return this.altIDField;
            }
            set
            {
                this.altIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string email_address
        {
            get
            {
                return this.email_addressField;
            }
            set
            {
                this.email_addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string contactPhone
        {
            get
            {
                return this.contactPhoneField;
            }
            set
            {
                this.contactPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public System.Nullable<int> empNo
        {
            get
            {
                return this.empNoField;
            }
            set
            {
                this.empNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string udf1
        {
            get
            {
                return this.udf1Field;
            }
            set
            {
                this.udf1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string udf2
        {
            get
            {
                return this.udf2Field;
            }
            set
            {
                this.udf2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string udf3
        {
            get
            {
                return this.udf3Field;
            }
            set
            {
                this.udf3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string udf4
        {
            get
            {
                return this.udf4Field;
            }
            set
            {
                this.udf4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public System.Nullable<int> branchNo
        {
            get
            {
                return this.branchNoField;
            }
            set
            {
                this.branchNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public System.Nullable<int> coNo
        {
            get
            {
                return this.coNoField;
            }
            set
            {
                this.coNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public System.Nullable<int> installNo
        {
            get
            {
                return this.installNoField;
            }
            set
            {
                this.installNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public System.Nullable<int> servcoNo
        {
            get
            {
                return this.servcoNoField;
            }
            set
            {
                this.servcoNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public System.Nullable<int> corpAcctNo
        {
            get
            {
                return this.corpAcctNoField;
            }
            set
            {
                this.corpAcctNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string startDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string tranDate
        {
            get
            {
                return this.tranDateField;
            }
            set
            {
                this.tranDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string endDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=33)]
        public System.Nullable<int> historyRows
        {
            get
            {
                return this.historyRowsField;
            }
            set
            {
                this.historyRowsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string openOnly
        {
            get
            {
                return this.openOnlyField;
            }
            set
            {
                this.openOnlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string invoiceOnly
        {
            get
            {
                return this.invoiceOnlyField;
            }
            set
            {
                this.invoiceOnlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string sortOrder
        {
            get
            {
                return this.sortOrderField;
            }
            set
            {
                this.sortOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string useHistory
        {
            get
            {
                return this.useHistoryField;
            }
            set
            {
                this.useHistoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string dbFlag
        {
            get
            {
                return this.dbFlagField;
            }
            set
            {
                this.dbFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string startBillCode
        {
            get
            {
                return this.startBillCodeField;
            }
            set
            {
                this.startBillCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string endBillCode
        {
            get
            {
                return this.endBillCodeField;
            }
            set
            {
                this.endBillCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string hideReverse
        {
            get
            {
                return this.hideReverseField;
            }
            set
            {
                this.hideReverseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string retAddr
        {
            get
            {
                return this.retAddrField;
            }
            set
            {
                this.retAddrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=43)]
        public System.Nullable<int> invFrom
        {
            get
            {
                return this.invFromField;
            }
            set
            {
                this.invFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=44)]
        public System.Nullable<int> invTo
        {
            get
            {
                return this.invToField;
            }
            set
            {
                this.invToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=45)]
        public System.Nullable<int> spid
        {
            get
            {
                return this.spidField;
            }
            set
            {
                this.spidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string emailFlag
        {
            get
            {
                return this.emailFlagField;
            }
            set
            {
                this.emailFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=47)]
        public System.Nullable<int> invFormNo
        {
            get
            {
                return this.invFormNoField;
            }
            set
            {
                this.invFormNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=48)]
        public System.Nullable<int> invoiceNo
        {
            get
            {
                return this.invoiceNoField;
            }
            set
            {
                this.invoiceNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=49)]
        public System.Nullable<int> ctactLinkNo
        {
            get
            {
                return this.ctactLinkNoField;
            }
            set
            {
                this.ctactLinkNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string processName
        {
            get
            {
                return this.processNameField;
            }
            set
            {
                this.processNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public decimal recdAmount
        {
            get
            {
                return this.recdAmountField;
            }
            set
            {
                this.recdAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public string serverName
        {
            get
            {
                return this.serverNameField;
            }
            set
            {
                this.serverNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public string dbName
        {
            get
            {
                return this.dbNameField;
            }
            set
            {
                this.dbNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nmccentral.com/webservices/nmcmapi")]
    public partial class OnTestParms
    {
        
        private System.Nullable<int> siteNoField;
        
        private System.Nullable<int> systemNoField;
        
        private System.Nullable<int> contactNoField;
        
        private string processFlagField;
        
        private string testCatIDField;
        
        private System.Nullable<int> testSeqNoField;
        
        private string effectiveDateField;
        
        private string expireDateField;
        
        private System.Nullable<int> extendHHField;
        
        private System.Nullable<int> extendMMField;
        
        private string testCommentField;
        
        private string allSystemsFlagField;
        
        private string allZonesFlagField;
        
        private string zonesListField;
        
        private string authPinField;
        
        private string pINField;
        
        private string zoneStateIDField;
        
        private string systemListField;
        
        private string servtype_idField;
        
        private string procNameField;
        
        private string eventIDField;
        
        private decimal alarmIncNoField;
        
        private string serverField;
        
        private string eventDateField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> siteNo
        {
            get
            {
                return this.siteNoField;
            }
            set
            {
                this.siteNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> systemNo
        {
            get
            {
                return this.systemNoField;
            }
            set
            {
                this.systemNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> contactNo
        {
            get
            {
                return this.contactNoField;
            }
            set
            {
                this.contactNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string processFlag
        {
            get
            {
                return this.processFlagField;
            }
            set
            {
                this.processFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string testCatID
        {
            get
            {
                return this.testCatIDField;
            }
            set
            {
                this.testCatIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> testSeqNo
        {
            get
            {
                return this.testSeqNoField;
            }
            set
            {
                this.testSeqNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string effectiveDate
        {
            get
            {
                return this.effectiveDateField;
            }
            set
            {
                this.effectiveDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string expireDate
        {
            get
            {
                return this.expireDateField;
            }
            set
            {
                this.expireDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<int> extendHH
        {
            get
            {
                return this.extendHHField;
            }
            set
            {
                this.extendHHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<int> extendMM
        {
            get
            {
                return this.extendMMField;
            }
            set
            {
                this.extendMMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string testComment
        {
            get
            {
                return this.testCommentField;
            }
            set
            {
                this.testCommentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string allSystemsFlag
        {
            get
            {
                return this.allSystemsFlagField;
            }
            set
            {
                this.allSystemsFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string allZonesFlag
        {
            get
            {
                return this.allZonesFlagField;
            }
            set
            {
                this.allZonesFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string zonesList
        {
            get
            {
                return this.zonesListField;
            }
            set
            {
                this.zonesListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string authPin
        {
            get
            {
                return this.authPinField;
            }
            set
            {
                this.authPinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string PIN
        {
            get
            {
                return this.pINField;
            }
            set
            {
                this.pINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string zoneStateID
        {
            get
            {
                return this.zoneStateIDField;
            }
            set
            {
                this.zoneStateIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string systemList
        {
            get
            {
                return this.systemListField;
            }
            set
            {
                this.systemListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string servtype_id
        {
            get
            {
                return this.servtype_idField;
            }
            set
            {
                this.servtype_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string procName
        {
            get
            {
                return this.procNameField;
            }
            set
            {
                this.procNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string eventID
        {
            get
            {
                return this.eventIDField;
            }
            set
            {
                this.eventIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public decimal alarmIncNo
        {
            get
            {
                return this.alarmIncNoField;
            }
            set
            {
                this.alarmIncNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string server
        {
            get
            {
                return this.serverField;
            }
            set
            {
                this.serverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string eventDate
        {
            get
            {
                return this.eventDateField;
            }
            set
            {
                this.eventDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface NMCLinkPortalSoapChannel : NMCServiceReference.NMCLinkPortalSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class NMCLinkPortalSoapClient : System.ServiceModel.ClientBase<NMCServiceReference.NMCLinkPortalSoap>, NMCServiceReference.NMCLinkPortalSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NMCLinkPortalSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(NMCLinkPortalSoapClient.GetBindingForEndpoint(endpointConfiguration), NMCLinkPortalSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NMCLinkPortalSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NMCLinkPortalSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NMCLinkPortalSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NMCLinkPortalSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NMCLinkPortalSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> ProcessDataAsync(string reqType, string secUser, string passWord, string csNo, string xmldata)
        {
            return base.Channel.ProcessDataAsync(reqType, secUser, passWord, csNo, xmldata);
        }
        
        public System.Threading.Tasks.Task<NMCServiceReference.ArrayOfXElement> ProcessAppRequestAsync(NMCServiceReference.InputParms inParms)
        {
            return base.Channel.ProcessAppRequestAsync(inParms);
        }
        
        public System.Threading.Tasks.Task<NMCServiceReference.ArrayOfXElement> ProcessDataElementRequestAsync(NMCServiceReference.InputParms inParms)
        {
            return base.Channel.ProcessDataElementRequestAsync(inParms);
        }
        
        public System.Threading.Tasks.Task<NMCServiceReference.ArrayOfXElement> ProcessDataElementRequest2Async(NMCServiceReference.OnTestParms ontestParms)
        {
            return base.Channel.ProcessDataElementRequest2Async(ontestParms);
        }
        
        public System.Threading.Tasks.Task<string> GetAppTokenAsync(string userName)
        {
            return base.Channel.GetAppTokenAsync(userName);
        }
        
        public System.Threading.Tasks.Task<string> ProcessTwilioRequestAsync(string twilioUser, string twilioPIN, string accountNo, string codeWord, string processName, string testHours, string testFlag, string userName, string eventSeqNo)
        {
            return base.Channel.ProcessTwilioRequestAsync(twilioUser, twilioPIN, accountNo, codeWord, processName, testHours, testFlag, userName, eventSeqNo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NMCLinkPortalSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.NMCLinkPortalSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NMCLinkPortalSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://www.alarmaccount.com/NMCTestPortal/NMCLinkPortal.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.NMCLinkPortalSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://www.alarmaccount.com/NMCTestPortal/NMCLinkPortal.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            NMCLinkPortalSoap,
            
            NMCLinkPortalSoap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.0.0.2")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
